version: "3.8"

services:
    github_api:
        build: ./github/
        container_name: github_api
        expose:
            - "5000"
        environment: 
            - FLASK_APP=api
            - FLASK_ENV=development

    build_android:
        build: ./build_android/
        container_name: build_android
        expose:
            - "5001"
        environment: 
            - FLASK_APP=api
            - FLASK_ENV=development
    
    proxy:
        build: ./proxy/
        container_name: proxy
        ports: 
            - "80:80"
        depends_on: 
            - github_api
            - build_android
